### ISSUE TITLE
Síntese de atividades - Bolsista Jaline Mombach

### ISSUE THREAD

**Issue by jalinegm** [Rede-DSBR/PNP#150]
# Síntese de atividades

## Pesquisadora Jaline Mombach

@jalinegm

## Outubro

- [x] Participação na reunião inicial com Prof. Poty para orientação aos bolsistas (16/10 às 10h)
- [x] Preparação da documentação para recebimento de bolsa - encaminhamentos no IFFar

## Novembro

- [x] Encaminhamento da documentação para bolsa em 01/11 - Processo IFFAR 23873.000707/2023-47
- [x] Instalação da Adobe Cloud e treinamento no Photoshop, Illustrator e After Effects
- [x] Participação em reunião DSBR sobre extrator PNP (07/11) - estudar LGPD
- [x] Estudo do Mapbox - https://www.mapbox.com/
      https://www.youtube.com/@MapboxOfficial e canal da Alice Drummond - https://www.youtube.com/watch?v=Dp2qcC4OSHE
- [x] Estudo do IconMap https://www.youtube.com/watch?v=W6zMS5W_GU0
- [x] #151

## Dezembro

- [x] Participação em reunião sobre o plano de trabalho individual (07/12)
- [x] Exploração do arquivo .pbix da PNP atual e estudo do modelo, das fórmulas e visuais usados
- [x] Participação nas sprints:
  - [x] Sprint 01. Conhecimento da Infraestrutura Atual e Estratégias Iniciais: 01 horas
  - [x] Sprint 02. Configuração inicial do Ambiente Azure: 02 horas
  - [x] Sprint 04. Proposição no ambiente Azure de pipeline para Dados Orçamentários: 02 horas
  - [x] Sprint 05. Apresentação e compreensão do consumo de dados orçamentários na Plataforma Nilo Peçanha 02 horas
- [x] Estudo da gravação da Sprint 03. Apresentação e compreensão de pipeline de Dados Orçamentários: 02 horas

## Janeiro
- [x] #152
- [x] #153 

Participação em reuniões:
- [x] Reunião anual do Revalide - 10/01, das 15h às 17h
- [x] Cursos FIC - 18/01, das 10h às 11h40min
- [x] Reunião com Prof. Brega (SETEC) sobre cursos FIC - 22/01, das 18h às 19h
- [x] #154 discussão e ajuste de slides criados com dados dos cursos FIC - 25/01, das 14h às 16h
- [x] Exploração da Azure com login enviado pelo Prof. Poty
- [x] #155 Criação de documento sobre cursos FIC em 12/01: https://docs.google.com/document/d/1MInTGVuidljt9i1MX9plGTfkuUBUrJQq4X9zC7hswF8/edit?usp=sharing

Participação nas sprints:

- [x] Sprint 07: Estruturação de Pipeline de Dados Orçamentários - 2h
- [x] Sprint 08: Hands on - Estruturação de Pipeline de Dados - 2h
- [x] Sprint 10: Qualificação de demanda - Estruturação de Pipeline de Dados Orçamentários
- [x] Sprint 11: Estruturação de esteira de dados na infraestrutura Azure - 2h
- [x] Visualização da gravação da Sprint 09: Qualificação de demanda - Estruturação de Pipeline de Dados Orçamentários

## Fevereiro

- [x] #158
- [x] Resposta ao Fale Conosco a respeito das cotas na PNP: https://docs.google.com/document/d/1mJck2imfpMB9HFx8CGPTzRGSgF4LWbWwbW5zftAIrYA/edit?usp=sharing / https://github.com/Rede-DSBR/PNP/issues/140
- [x] #156
- [x] #157
- [ ] #159

Participação em reuniões:

- [x] Reunião sobre os dados de reserva de vagas - 02/02, das 17h às 18h
- [x] Reunião com Prof. Duda e Prof. Poty sobre a pesquisa com usuários - 09/02, das 16h30min às 17h30min
- [x] Reunião com equipe PNP sobre as demandas SETEC, 27/02, das 20h30min às 23h

Participação nas sprints:

- [x] Sprint 12: Apresentação técnica do processos de ETL dos dados orçamentários - 2h
- [x] Sprint 13: Construção do Data Flow - 2h
- [x] Sprint 14: Estruturação de Pipeline de dados do Portal do Orçamento do Siop - 2h
- [x] Sprint 15: Desenvolvimento de Staging Area em nuvem Azure - 2h
- [x] Sprint 16: Modelo de dados da PNP - 2h

## Março

- [x] Resposta ao Fale Conosco #149 
- [ ] #153 (continuação)
- [x] #151 (continuação)

Participação em reuniões:

- [x] Reunião sobre os dados de reserva de vagas - 02/02, das 17h às 18h
- [x] Zapchat - bate-papo com Gustavo, 07/03, das 21h às 21h30min
- [x] Reunião PNP e Revalide, 18/03, das 9h às 11h
- [x] Reunião para Análise de Notícia na Imprensa: [Ampliação de Institutos Federais é boa notícia, mas impacto é
restrito](https://oglobo.globo.com/brasil/antonio-gois/coluna/2024/03/ampliacao-de-institutos-federais-e-boa-noticia-mas-impacto-e-restrito.ghtml), 19/03, das 15h às 16h
- [x] Reunião para conversa sobre o índice de verticalização da PNP, 24/03, das 22h às 23h - #162 
- [x] Reunião sobre o evento de indicadores, 27/03, das 10h às 11h #172 

Participação nas sprints:

- [x] Sprint 17: Recursos da plataforma de dados Azure - 2h
- [x] Sprint 18: Discussão sobre a infraestrutura de Dados - 2h

## Abril

- [x] #172 
- [x] #190 
- [x] #192
- [x] #182 
- [x] #183
- [ ] Análise dos dados da prévia da PNP 2024
- [x] #197
- [x] #198

Participação em reuniões:

- [x] Evento de indicadores, 03/04, das 14h30min às 15h30min  #172 
- [x] Evento de indicadores, 08/04, das 17h às 18h
- [x] Análise da prévia PNP 2024, 09/04 das 11h às 12h
- [x] Brainstorming com Prof. Duda, 11/04, às 17h
- [x] Atualizações da prévia PNP 2024, 15/04, das 11h às 12h
- [x] Atualizações da prévia PNP 2024, 16/04, das 10h30min às 11h
- [x] Pesquisadores Institucionais, 17/04, das 17h às 18h
- [x] Atualizações da prévia PNP 2024, 22/04, das 9h às 9h30min
- [x] Análise prospectiva e arquitetura de Dados do Caged, Cadastro geral de empregados e desempregados, 22/04, das 11h às 12h
- [x] Atualizações da prévia PNP 2024, 22/04, das 13h30min  às 14h
- [x] Validação de dados com Marcus Vinícius, 22/04, das 19h às 20h
- [x] Acesso aos arquivos PNP, 23/04, das 9h às 9h30min
- [x] Reunião com Cristina para extração dos dados de PROEJA no Sistec, 23/04, das 10h às 10h30min
- [x] Apresentação Monitor de Acessos e Chatbot PNP, 23/04, das 14h15min às 15h30min
- [x] Reunião com Cristina sobre Sistec, 24/04, das 16h às 16h30min
- [x] Atualizações da prévia PNP 2024, 26/04, das 10h  às 10h30min
- [x] Base de servidores PNP 2024, 29/04, das 10h  às 11h
- [x] Ajuste com Breno - PNP 2024, 29/04, das 11h40min  às 12h20min
- [x] Atualizações da prévia PNP 2024, 29/04, das 16h30min  às 17h30min
- [x] Ajuste PROEJA com Shirlane PNP 2024, 30/04, das 16h30min  às 17h

## Maio

- [x] #184
- [x] #196 
- [x] #172
- [x] Registro de correções para PNP: https://www.canva.com/design/DAGBIm2tAIE/Pq_SUAlzIKtltr7OUJsMmA/edit
- [x] Análise dos dados da prévia da PNP 2024
- [x] #202 

Participação em reuniões:

- [x] Discussão dos dados do IFTO e IFSUDESTEMINAS, 13/05, das 14h às 15h
- [x] Escuta de sugestões do IFPI (PI Diego), 15/05, das 9h às 10h
- [x] Conversa com Breno para entender o conceito de matrícula atendida na Revalide, 17/05, das 10h às 10h45min
- [x] Escuta de sugestões do IFSUDESTEMINAS (PI Alexandre), 17/05, das 11h às 12h.
- [x] Conversa com Cristina sobre as inconsistências de matrícula atendida identificadas, 23/05, das 14h às 15h
- [x] Escuta de sugestões do IFTO (PI Eder), 23/05, das 15h às 16h
- [x] Microdados PNP com Cristina, 28/05, das 16h30min às 17h

# Junho

- [x] #201 
- [x] #200 
- [x] Apoio na escrita das metas 3 e 9 no Relatório Parcial do Termo de Execução Descentralizada 12.535/2023, Plataforma Nilo Peçanha: Democratização de Dados da RFEPCT, Secretaria de Educação Profissional e Tecnológica - SETEC, dia 16 de junho.
- [x] Apoio à consulta de dados da PNP pelo formulário de demandas
- [x] #204 

Participação em reuniões:

- [x] Renovação do Projeto, 05/06, das 9h às 10h
- [x] Proposições para ABI no SISTEC, Revalide e PNP BI, 06/06, das 19h às 20h
- [x] Reunião - ABI SISTEC, 07/06, 16h30min às 17h
- [x] Reunião com grupo de especialistas PNP, dia 20 de junho, às 10h.

**Comment by jalinegm** [comment]
A partir do projeto PNP-ODI, adequação ao novo modelo de relatório.
