### ISSUE TITLE
📑 Plano Individual de Trabalho - Jaline Mombach

### ISSUE THREAD

**Issue by jalinegm** [Rede-DSBR/PNP#84]
# Pesquisadora

@jalinegm

# Problema Crítico

## Versão "pocket" da PNP

O telefone celular é o dispositivo mais utilizado pelos brasileiros para conexão à internet, segundo dados recentes da pesquisa TIC Domicílios 2023. Essa pesquisa é realizada pelo Centro Regional de Estudos para o Desenvolvimento da Sociedade da Informação (Cetic.br) e apresenta o panorama de uso da internet no país.

Dessa maneira, há demanda para que a PNP tenha uma versão de acesso móvel. Atualmente, o Power BI apresenta limitações para criação de versões responsivas dos relatórios publicados. Assim, faz-se necessário um estudo para adaptação dos dados e design de uma painel com dimensões preferenciais para telas de _smartphones_.

>Fonte: CGI.br/NIC.br, Centro Regional de Estudos para o Desenvolvimento da Sociedade da Informação (Cetic.br), Pesquisa sobre o uso das tecnologias de informação e comunicação nos domicílios brasileiros - TIC Domicílios 2023. Disponível em: https://data.cetic.br/explore/?pesquisa_id=1&unidade=Usu%C3%A1rios

# Meta do Plano de Trabalho

O problema elencado está diretamente vinculado às Metas 1, 2 e 3 no que diz respeito à a criação de ferramentas e interfaces de visualização interativas para exploração, análise, monitoramento, transparência e apoio à tomada de decisões.

# Como Pretende Resolver o Problema

- [ ] **Análise do _dashboard_ atual:** análise dos dados mais relevantes disponíveis na atual PNP, verificandos os tipos de visuais utilizados no Power BI para possível adaptação em tamanho de tela para dispositivos móveis.
- [ ] **Proposição de _views_ para a PNP versão móvel:** prototipação de telas adaptadas das informações da PNP atual para avaliação da equipe e possíveis usuários.
- [ ] **Criação de _dashboard_ adaptado:** após validação com a equipe, criação de _views_ no Power BI, visando o tamanho convencional de telas de dispositivos móveis e a adaptação automática do relatório publicado para essas telas.
- [ ] **Investigação do _layout móvel_ no Power BI:** edição do layout móvel para acesso pelo aplicativo do Power BI.

# Outras Atividades

Além das atividades elencadas no problema crítico, também poderá ter atuação nas _issues_ já estipuladas, caso a equipe solicite apoio:

- [ ] Avaliação de usabilidade e condução de estudo com usuários (referentes à Meta 8)
- [ ] Colaboração no desenvolvimento do novo _Design System_ da PNP
- [ ] Colaboração na construção de metáforas visuais, publicação de panorama de indicadores (_issue_ #19)
- [ ] Colaboração na revisão do guia de referência metodológica(_issue_ #22)
- [ ] Colaboração na criação de relatórios, gráficos, vídeos e outros artefatos que divulguem os dados presentes na PNP (_issue_ #29)

# Recursos Necessários

- [x] Acesso ao drive dos arquivos da PNP
- [x] Figma
- [x] Aplicações da Adobe Cloud: Photoshop, Illustrator, After Effects
- [x] Canva Pro

# Entregáveis do Plano de Trabalho

- [ ] 📱 Protótipos no Figma
- [ ] 🔎 Relatório de avaliação de usabilidade com usuários
- [ ] 📊 Nova página de visualização de dados da PNP versão mobile no Power BI

# Materiais de Referência

1. Mobile Application User Experience Checklist. Disponível em: https://mauxc.com/
2. R. Parente Da Costa, E. D. Canedo, R. T. De Sousa, R. De Oliveira Albuquerque and L. J. García Villalba, "Set of Usability Heuristics for Quality Assessment of Mobile Applications on Smartphones," in IEEE Access, vol. 7, pp. 116145-116161, 2019, doi: 10.1109/ACCESS.2019.2910778.
3. Web Content Accessibility Guidelines (WCAG) 2.1. Disponível em: https://www.w3.org/TR/WCAG21/
4. APCA: the new algorithm for accessible colour contrast. Disponível em: https://ruitina.com/apca-accessible-colour-contrast/

# Pasta de Arquivos

📁 Pasta de Arquivos do Plano de Trabalho
https://github.com/jalinegm/Rede-DSBR.git

# Organização do Trabalho

## Síntese das atividades realizadas
📝 #150 

## Frequência de Reuniões de Atualização

Reuniões quinzenais, quintas-feiras à tarde.
Há flexibilidade para alteração do dia da semana e horários, ajustados conforme demanda da equipe.

## Data de Início

out/2023

## Data de Conclusão Prevista

mar/2024

**Comment by RedeDSBR** [comment]
Olá @jalinegm !

🎉 **Parabéns** pela elaboração do plano de trabalho para a versão móvel da PNP. A proposta assimila com profundidade as necessidades do projeto, alinhando-se perfeitamente com as expectativas em criar ferramentas e interfaces interativas para ampliar a capacidade de informação e de disseminação dos dados da PNP.

A ênfase na adaptação para dispositivos móveis é de extrema relevância, considerando a alta prevalência do uso de smartphones no Brasil. Sua abordagem, que inclui a análise do dashboard atual, prototipação de telas para a versão móvel, e criação de um dashboard adaptado no Power BI, complementa de maneira significativa os objetivos do projeto principal, destacando aspectos-chave de acessibilidade e usabilidade de dados.

Contudo, gostaríamos de ressaltar um aspecto importante relacionado ao cronograma. O projeto principal visa lançar a PNP em março, e seria ideal que a versão móvel estivesse disponível nesse período. Reconhecemos que isso pode representar um desafio adicional, mas estamos confiantes na sua capacidade de adaptar o plano para alcançar esse novo objetivo.

Fiquei entusiasmado com a sua contribuição e estou aqui à disposição para discutir ajustes no cronograma para atender a essa nova meta. Sua expertise e abordagem inovadora são fundamentais para o sucesso do projeto, e estamos ansiosos para ver os resultados de sua valiosa contribuição.

**Excelente trabalho 🤝**, será um passo em nossa jornada inovadora da PNP 🚀

**Comment by jalinegm** [comment]
Corrigi o período e acrescentei uma síntese de atividades que estou fazendo para facilitar a organização: https://github.com/jalinegm/Rede-DSBR/blob/main/relatorioAtividades_Jaline.md

**Comment by jalinegm** [comment]
As atividades realizadas estão descritas na issue https://github.com/Rede-DSBR/PNP/issues/150
